export const data = [
  {
    nombres: "juan",
    apellidos: "trujillo",
    correo: "joseltru@admin.com",
    edad: 29,
    salario: 100,
    cargo: "ingeniero",
  },
  {
    nombres: "jorge",
    apellidos: "trujillo",
    correo: "jorge@admin.com",
    edad: 29,
    salario: 100,
    cargo: "ingeniero",
  },
  {
    nombres: "jug3an",
    apellidos: "trujillo",
    correo: "j2rfa@admin.com",
    edad: 29,
    salario: 100,
    cargo: "ingeniero",
  },
  {
    nombres: "jufafsan",
    apellidos: "trujillo",
    correo: "fghrd@admin.com",
    edad: 29,
    salario: 100,
    cargo: "ingeniero",
  },
  {
    nombres: "fhgdafd",
    apellidos: "trujillo",
    correo: "geasfafa@admin.com",
    edad: 29,
    salario: 100,
    cargo: "ingeniero",
  },
  {
    nombres: "pinocha",
    apellidos: "trujillo",
    correo: "pinocha@admin.com",
    edad: 29,
    salario: 100,
    cargo: "ingeniero",
  },
  {
    nombres: "otrsd",
    apellidos: "trujillo",
    correo: "gagasfaw@admin.com",
    edad: 29,
    salario: 100,
    cargo: "ingeniero",
  },
  {
    nombres: "maria",
    apellidos: "trujillo",
    correo: "maria@admin.com",
    edad: 29,
    salario: 100,
    cargo: "ingeniero",
  },
  {
    nombres: "glkadiz",
    apellidos: "trujillo",
    correo: "agaojha@admin.com",
    edad: 29,
    salario: 100,
    cargo: "ingeniero",
  },
  {
    nombres: "laura",
    apellidos: "trujillo",
    correo: "laura@admin.com",
    edad: 29,
    salario: 100,
    cargo: "ingeniero",
  },
];



